import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {ReactNode} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <h1>hello rasool</h1>
    <ul>
      <li>
        <Link href="/">home</Link>
      </li>
      <li>
        <Link href="/about">about</Link>
      </li>
      <li>
        <Link href="/contact-us">contact us</Link>
      </li>
    </ul>
    <h2>articles</h2>
    <ul>
      <li>
        <Link href="/articles?title=article-1&id=1">article 1</Link>
      </li>
      <li>
        <Link href="/articles?title=article-2&id=2">article 2</Link>
      </li>
      <li>
        <Link href="/articles?title=article-3&id=3">article 3</Link>
      </li>
    </ul>
    <h1>book</h1>
    <li>
      <Link href="/book/[title]/[id]" as='/book/book-1/2'>book </Link>
    </li>
    {children}
    </body>
    </html>
  )
}